/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SoundcloudType = {
  _id: string;
  _type: 'soundcloudType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  trackId?: string;
};

export type ConcertType = {
  _id: string;
  _type: 'concertType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  slug?: Slug;
  buyTicketLink?: string;
  available?: boolean;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  eventVideos?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'video';
  }>;
  date?: string;
  subHeading?: string;
  description?: string;
  location?: string;
};

export type EventsType = {
  _id: string;
  _type: 'eventsType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  slug?: Slug;
  available?: boolean;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bannerImage?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  eventVideos?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'video';
  }>;
  date?: string;
  subHeading?: string;
  description?: string;
  location?: string;
  contactFormHeading?: string;
  messages?: Array<{
    name?: string;
    email?: string;
    phone?: string;
    message?: string;
    createdAt?: string;
    _type: 'message';
    _key: string;
  }>;
};

export type TitleDescriptionType = {
  _id: string;
  _type: 'titleDescriptionType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  floatingImage?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
};

export type BannerType = {
  _id: string;
  _type: 'bannerType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heading?: string;
  subHeading?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  bannerImageMobile?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  bannerImage?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  bannerTitle?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
};

export type EkontSenderDetails = {
  _id: string;
  _type: 'ekontSenderDetails';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  senderClient?: {
    name?: string;
    phones?: Array<string>;
    email?: string;
  };
  senderAddress?: {
    city?: string;
    postCode?: string;
    street?: string;
    num?: string;
    other?: string;
  };
  senderDeliveryType?: 'office' | 'delivery';
  cdOptions?: {
    method?: 'bank';
    bic?: string;
    iban?: string;
    bankCurrency?: 'EUR' | 'BGN';
    payDays?: number;
  };
  senderOfficeCode?: string;
  payAfterAccept?: '1' | '0';
  payAfterTest?: '1' | '0';
  shipmentDescription?: string;
  paymentSenderMethod?: 'cash' | 'credit';
  paymentSenderAmount?: string;
  paymentReceiverMethod?: 'cash';
  paymentReceiverAmount?: string;
  returnInstructionParams?: {
    type?: 'return';
    returnParcelDestination?: string;
    returnParcelPaymentSide?: 'sender' | 'receiver';
    returnParcelReceiverOfficeCode?: string;
  };
};

export type YoutubeVideos = {
  _id: string;
  _type: 'youtubeVideos';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: 'music' | 'esoterica';
  videoTitle?: string;
  url?: string;
};

export type CardsType = {
  _id: string;
  _type: 'cardsType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sectionTitle?: string;
  slug?: Slug;
  sectionSubheading?: string;
  cards?: Array<{
    title?: string;
    slug?: Slug;
    description?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
          listItem?: 'bullet';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
          _key: string;
        }
    >;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
    _key: string;
  }>;
};

export type Design = {
  _id: string;
  _type: 'design';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  presentation?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
};

export type ContactForm = {
  _id: string;
  _type: 'contactForm';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  registeredName?: string;
  registeredEmail?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phoneNumber?: string;
  message?: string;
};

export type Tag = {
  _id: string;
  _type: 'tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type SalesType = {
  _id: string;
  _type: 'salesType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
};

export type ContactInfo = {
  _id: string;
  _type: 'contactInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: string;
  heading?: string;
  contacts?: Array<{
    title?: string;
    phone?: string;
    email?: string;
    other?: string;
    _key: string;
  }>;
};

export type Order = {
  _id: string;
  _type: 'order';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerDetails?: {
    customerName?: string;
    customerEmail?: string;
    customerPhone?: string;
  };
  customerAddress?: {
    country?: string;
    city?: string;
    officeCode?: string;
    zip?: string;
    street?: string;
    streetNumber?: string;
    other?: string;
  };
  stripePaymentIntentId?: string;
  products?: Array<{
    product?:
      | {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'musicStore';
        }
      | {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'esotericaStore';
        };
    quantity?: number;
    selectedSize?: string;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  deliveryMethod?: string;
  paymentMethod?: string;
  status?:
    | 'pending'
    | 'inProgress'
    | 'ready'
    | 'failed'
    | 'canceled'
    | 'refunded'
    | 'send';
  wasLabelPatched?: boolean;
  labelURL?: string;
  labelAsset?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    _type: 'file';
  };
  orderDate?: string;
};

export type EsotericaStore = {
  _id: string;
  _type: 'esotericaStore';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  Name?: string;
  slug?: Slug;
  type?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  productVideo?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'video';
  };
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  price?: number;
  discount?: number;
  category?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  stock?: number;
  showSizes?: boolean;
  sizes?: Array<string>;
  date?: string;
};

export type MusicStore = {
  _id: string;
  _type: 'musicStore';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  Name?: string;
  type?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  productVideo?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'video';
  };
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  price?: number;
  discount?: number;
  category?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  stock?: number;
  showSizes?: boolean;
  sizes?: Array<string>;
  date?: string;
};

export type Video = {
  _id: string;
  _type: 'video';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  thumbnail?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  videoFile?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    _type: 'file';
  };
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type ImageType = {
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: 'image';
  _key: string;
};

export interface BentoGridGalleryProps {
  data: {
    title?: string;
    heading?: string;
    slug?: Slug;
    images?: ImageType[];
    totalImages?: number;
    currentPage?: number;
    totalPages?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
    eventVideos?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'video';
      videoFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        url: string | null;
        _type: 'file';
      };
    }>;
  };
  styles?: string;
}
export type SocialMediaType = {
  _rev?: string;
  _createdAt?: string;
  _updatedAt?: string;
  _type?: 'reference';
  _id: string;
  [internalGroqTypeReferenceTo]?: 'sanity.socialMediaType';
  title?: string;
  url?: string;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  };
};

export type LayoutProps = {
  _id: string;
  _type: 'sanity.sidebarType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  header?: string;
  links?: Array<{
    _type?: 'reference';
    _key?: string;
    slug?: Slug;
    [internalGroqTypeReferenceTo]?: 'sanity.page';
    title?: string;
  }>;
  socialMedia?: Array<SocialMediaType>;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | SoundcloudType
  | ConcertType
  | EventsType
  | TitleDescriptionType
  | BannerType
  | EkontSenderDetails
  | YoutubeVideos
  | CardsType
  | Design
  | ContactForm
  | Tag
  | SalesType
  | ContactInfo
  | Order
  | EsotericaStore
  | MusicStore
  | Video
  | SanityFileAsset
  | Category
  | Slug
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | LayoutProps
  | ImageType
  | SocialMediaType
  | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/banner/getBannerByTitle.ts
// Variable: BANNER_BY_TITLE_QUERY
// Query: *[_type == "bannerType" && slug == $slug][0]
export type BANNER_BY_TITLE_QUERYResult = {
  _id: string;
  _type: 'bannerType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: string;
  heading?: string;
  subHeading?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  bannerImageMobile?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  bannerImage?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  bannerTitle?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
} | null;

// Source: ./sanity/lib/categories/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[ _type == "category"]
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  slug?: Slug;
  description?: string;
}>;

// Source: ./sanity/lib/categories/getCategoriesByTag.ts
// Variable: ALL_CATEGORIES_QUERY_BY_TAG
// Query: *[_type == "category" && references(*[_type == "tag" && _id == $tags]._id)] | order(Name asc)
export type ALL_CATEGORIES_QUERY_BY_TAGResult = Array<{
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  slug?: Slug;
  description?: string;
}>;

// Source: ./sanity/lib/categories/getContactInfo.ts
// Variable: CONTACT_CARDS_QUERY
// Query: *[ _type == "contactInfo" && slug == $slug][0]
export type CONTACT_CARDS_QUERYResult = {
  _id: string;
  _type: 'contactInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: string;
  heading?: string;
  contacts?: Array<{
    title?: string;
    phone?: string;
    email?: string;
    other?: string;
    _key: string;
  }>;
} | null;

// Source: ./sanity/lib/categories/getPageCards.ts
// Variable: PAGE_CARDS_QUERY
// Query: *[ _type == "cardsType" && slug.current == $slug][0]
export type PAGE_CARDS_QUERYResult = {
  _id: string;
  _type: 'cardsType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sectionTitle?: string;
  slug?: Slug;
  sectionSubheading?: string;
  cards?: Array<{
    title?: string;
    slug?: Slug;
    description?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
          listItem?: 'bullet';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
          _key: string;
        }
    >;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }>;
    _key: string;
  }>;
} | null;

// Source: ./sanity/lib/ekont/senderDetails.ts
// Variable: EKONT_SENDER_DETAILS_QUERY
// Query: *[ _type == "ekontSenderDetails"]
export type EKONT_SENDER_DETAILS_QUERYResult = Array<{
  _id: string;
  _type: 'ekontSenderDetails';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  senderClient?: {
    name?: string;
    phones?: Array<string>;
    email?: string;
  };
  senderAddress?: {
    city?: string;
    postCode?: string;
    street?: string;
    num?: string;
    other?: string;
  };
  senderDeliveryType?: 'delivery' | 'office';
  cdOptions?: {
    method?: 'bank';
    bic?: string;
    iban?: string;
    bankCurrency?: 'BGN' | 'EUR';
    payDays?: number;
  };
  senderOfficeCode?: string;
  payAfterAccept?: '0' | '1';
  payAfterTest?: '0' | '1';
  shipmentDescription?: string;
  paymentSenderMethod?: 'cash' | 'credit';
  paymentSenderAmount?: string;
  paymentReceiverMethod?: 'cash';
  paymentReceiverAmount?: string;
  returnInstructionParams?: {
    type?: 'return';
    returnParcelDestination?: string;
    returnParcelPaymentSide?: 'receiver' | 'sender';
    returnParcelReceiverOfficeCode?: string;
  };
}>;

// Source: ./sanity/lib/events/getConcerts.ts
// Variable: CONCERTS_QUERY
// Query: *[ _type == "concertType"] | order(_createdAt asc)
export type CONCERTS_QUERYResult = Array<{
  _id: string;
  _type: 'concertType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  slug?: Slug;
  buyTicketLink?: string;
  available?: boolean;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  eventVideos?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'video';
  }>;
  date?: string;
  subHeading?: string;
  description?: string;
  location?: string;
}>;

// Source: ./sanity/lib/events/getConcertsBySlug.ts
// Variable: CONCERTS_QUERY_BY_SLUG
// Query: *[ _type == "concertType" && slug.current == $slug] | order(_createdAt desc)[0]
export type CONCERTS_QUERY_BY_SLUGResult = {
  _id: string;
  _type: 'concertType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  slug?: Slug;
  buyTicketLink?: string;
  available?: boolean;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  eventVideos?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'video';
  }>;
  date?: string;
  subHeading?: string;
  description?: string;
  location?: string;
} | null;

// Source: ./sanity/lib/events/getEvents.ts
// Variable: EVENTS_QUERY
// Query: *[ _type == "eventsType"] | order(_createdAt asc)    { ...,    "messages": undefined    }
export type EVENTS_QUERYResult = Array<{
  _id: string;
  _type: 'eventsType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  slug?: Slug;
  available?: boolean;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  eventVideos?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'video';
  }>;
  date?: string;
  subHeading?: string;
  description?: string;
  location?: string;
  contactFormHeading?: string;
  messages: null;
}>;

// Source: ./sanity/lib/events/getEventsBySlug.ts
// Variable: EVENTS_QUERY_BY_SLUG
// Query: *[ _type == "eventsType" && slug.current == $slug] | order(_createdAt desc) [0] {      ...,      "messages": undefined    }
export type EVENTS_QUERY_BY_SLUGResult = {
  _id: string;
  _type: 'eventsType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  slug?: Slug;
  available?: boolean;
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  eventVideos?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'video';
  }>;
  date?: string;
  subHeading?: string;
  description?: string;
  location?: string;
  contactFormHeading?: string;
  messages: null;
} | null;

// Source: ./sanity/lib/favorites/getFavoriteProducts.ts
// Variable: FAVORITE_PRODUCTS_QUERY
// Query: *[_type == "favoriteProducts" && userId == $userId][0] {    ...,    userId,    itemId[]-> {      _id,      Name,      ...,    }  }
export type FAVORITE_PRODUCTS_QUERYResult = null;

// Source: ./sanity/lib/orders/getOrders.ts
// Variable: ORDERS_QUERY
// Query: *[_type == "order" && clerkUserId == $userId] | order(_createdAt desc) {        ...,        products[]{          ...,          product->        },      }
export type ORDERS_QUERYResult = Array<{
  _id: string;
  _type: 'order';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerDetails?: {
    customerName?: string;
    customerEmail?: string;
    customerPhone?: string;
  };
  customerAddress?: {
    country?: string;
    city?: string;
    officeCode?: string;
    zip?: string;
    street?: string;
    streetNumber?: string;
    other?: string;
  };
  stripePaymentIntentId?: string;
  products: Array<{
    product:
      | {
          _id: string;
          _type: 'esotericaStore';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          Name?: string;
          slug?: Slug;
          type?: Array<{
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            _key: string;
            [internalGroqTypeReferenceTo]?: 'tag';
          }>;
          images?: Array<{
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
            _key: string;
          }>;
          productVideo?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'video';
          };
          description?: Array<
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: 'span';
                  _key: string;
                }>;
                style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
                listItem?: 'bullet';
                markDefs?: Array<{
                  href?: string;
                  _type: 'link';
                  _key: string;
                }>;
                level?: number;
                _type: 'block';
                _key: string;
              }
            | {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
                };
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                _type: 'image';
                _key: string;
              }
          >;
          price?: number;
          discount?: number;
          category?: Array<{
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            _key: string;
            [internalGroqTypeReferenceTo]?: 'category';
          }>;
          stock?: number;
          showSizes?: boolean;
          sizes?: Array<string>;
        }
      | {
          _id: string;
          _type: 'musicStore';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          Name?: string;
          type?: Array<{
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            _key: string;
            [internalGroqTypeReferenceTo]?: 'tag';
          }>;
          slug?: Slug;
          images?: Array<{
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
            _key: string;
          }>;
          productVideo?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'video';
          };
          description?: Array<
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: 'span';
                  _key: string;
                }>;
                style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
                listItem?: 'bullet';
                markDefs?: Array<{
                  href?: string;
                  _type: 'link';
                  _key: string;
                }>;
                level?: number;
                _type: 'block';
                _key: string;
              }
            | {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
                };
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                _type: 'image';
                _key: string;
              }
          >;
          price?: number;
          discount?: number;
          category?: Array<{
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            _key: string;
            [internalGroqTypeReferenceTo]?: 'category';
          }>;
          stock?: number;
          showSizes?: boolean;
          sizes?: Array<string>;
        }
      | null;
    quantity?: number;
    selectedSize?: string;
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  deliveryMethod?: string;
  paymentMethod?: string;
  status?:
    | 'canceled'
    | 'failed'
    | 'inProgress'
    | 'pending'
    | 'ready'
    | 'refunded'
    | 'send';
  wasLabelPatched?: boolean;
  labelURL?: string;
  labelAsset?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    _type: 'file';
  };
  orderDate?: string;
}>;

// Source: ./sanity/lib/products/getAllProducst.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "musicStore" || _type == "esotericaStore" ] | order(Name asc) {  Name,  stock,  price,  discount,  _id,  image,  images[]{        asset->,        hotspot,        crop,        _type,        _key      },  slug,  category[]->{title}}
export type ALL_PRODUCTS_QUERYResult = Array<{
  Name: string | null;
  stock: number | null;
  price: number | null;
  discount: number | null;
  _id: string;
  image: null;
  images: Array<{
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    _type: 'image';
    _key: string;
  }> | null;
  slug: Slug | null;
  category: Array<{
    title: string | null;
  }> | null;
}>;

// Source: ./sanity/lib/products/getEsotericaStoreProducts.ts
// Variable: ESOTERICA_PRODUCTS_QUERY
// Query: *[_type == "esotericaStore"] | order(Name asc) {      Name,      stock,      price,      discount,      _id,      image,      images[]{        asset->,        hotspot,        crop,        _type,        _key      },      slug,      showSizes,      sizes,      category[]->{title},      _type,          _createdAt,      _updatedAt,      _rev,      // images[]->,      // productVideo->,            }
export type ESOTERICA_PRODUCTS_QUERYResult = Array<{
  Name: string | null;
  stock: number | null;
  price: number | null;
  discount: number | null;
  _id: string;
  image: null;
  images: Array<{
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    _type: 'image';
    _key: string;
  }> | null;
  slug: Slug | null;
  showSizes: boolean | null;
  sizes: Array<string> | null;
  category: Array<{
    title: string | null;
  }> | null;
  _type: 'esotericaStore';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
}>;

// Source: ./sanity/lib/products/getMusicStoreProducts.ts
// Variable: MUSIC_PRODUCTS_QUERY
// Query: *[_type == "musicStore"] | order(Name asc) {      Name,      stock,      price,      discount,      _id,      image,      images[]{        asset->,        hotspot,        crop,        _type,        _key      },      slug,      showSizes,      sizes,      category[]->{title},      _type,          _createdAt,      _updatedAt,      _rev,      // images[]->,      // productVideo->,          }
export type MUSIC_PRODUCTS_QUERYResult = Array<{
  Name: string | null;
  stock: number | null;
  price: number | null;
  discount: number | null;
  _id: string;
  image: null;
  images: Array<{
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    _type: 'image';
    _key: string;
  }> | null;
  slug: Slug | null;
  showSizes: boolean | null;
  sizes: Array<string> | null;
  category: Array<{
    title: string | null;
  }> | null;
  _type: 'musicStore';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
}>;

// Source: ./sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[  _type in ["musicStore", "esotericaStore"] && slug.current == $slug] | order(Name asc) [0] {  ...,  category[]->,  images[]{    asset->,    hotspot,    crop,    _type,    _key  },  productVideo->{    _id,    _type,    title,    'videoFile': videoFile.asset->{      url    },    'thumbnail': thumbnail[].asset->{      url    },  }}  //  *[_type in ["musicStore", "esotericaStore"] && slug.current == $slug] | order(Name asc) [0] {  //     ...,  //     category[]->,  //     images[]{  //       asset->,  //       hotspot,  //       crop,  //       _type,  //       _key  //     },  //     productVideo->{  //       // thumbnail[]{  //       //   asset->{url}  //       // },  //       // videoFile->{  //       //   asset->{url}  //       // }  //       ...,  //       'thumbnail': thumbnail[].asset->,  //       'videoFile': videoFile.asset->  //     }  //   }
export type PRODUCT_BY_SLUG_QUERYResult =
  | {
      _id: string;
      _type: 'esotericaStore';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      Name?: string;
      slug?: Slug;
      type?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'tag';
      }>;
      images: Array<{
        asset: {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        _type: 'image';
        _key: string;
      }> | null;
      productVideo: {
        _id: string;
        _type: 'video';
        title: string | null;
        videoFile: {
          url: string | null;
        } | null;
        thumbnail: Array<{
          url: string | null;
        } | null> | null;
      } | null;
      description?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      price?: number;
      discount?: number;
      category: Array<{
        _id: string;
        _type: 'category';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        type?: Array<{
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          _key: string;
          [internalGroqTypeReferenceTo]?: 'tag';
        }>;
        slug?: Slug;
        description?: string;
      }> | null;
      stock?: number;
      showSizes?: boolean;
      sizes?: Array<string>;
    }
  | {
      _id: string;
      _type: 'musicStore';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      Name?: string;
      type?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'tag';
      }>;
      slug?: Slug;
      images: Array<{
        asset: {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        _type: 'image';
        _key: string;
      }> | null;
      productVideo: {
        _id: string;
        _type: 'video';
        title: string | null;
        videoFile: {
          url: string | null;
        } | null;
        thumbnail: Array<{
          url: string | null;
        } | null> | null;
      } | null;
      description?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      price?: number;
      discount?: number;
      category: Array<{
        _id: string;
        _type: 'category';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        type?: Array<{
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          _key: string;
          [internalGroqTypeReferenceTo]?: 'tag';
        }>;
        slug?: Slug;
        description?: string;
      }> | null;
      stock?: number;
      showSizes?: boolean;
      sizes?: Array<string>;
    }
  | null;

// Source: ./sanity/lib/products/searchProductsByName.ts
// Variable: SEARCH_PRODUCTS_BY_NAME_QUERY
// Query: *[      _type in ["musicStore", "esotericaStore", "concertType", "eventsType"]       && Name match $searchParams || title match $searchParams || heading match $searchParams || subHeading match $searchParams || location match $searchParams || description match $searchParams      || pt::text(description) match $searchParams      ] | order(Name asc)
export type SEARCH_PRODUCTS_BY_NAME_QUERYResult = Array<
  | {
      _id: string;
      _type: 'bannerType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: string;
      heading?: string;
      subHeading?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      bannerImageMobile?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      bannerImage?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      bannerTitle?: string;
      description?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
    }
  | {
      _id: string;
      _type: 'cardsType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      sectionTitle?: string;
      slug?: Slug;
      sectionSubheading?: string;
      cards?: Array<{
        title?: string;
        slug?: Slug;
        description?: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: 'span';
                _key: string;
              }>;
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
              listItem?: 'bullet';
              markDefs?: Array<{
                href?: string;
                _type: 'link';
                _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
            }
          | {
              asset?: {
                _ref: string;
                _type: 'reference';
                _weak?: boolean;
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: 'image';
              _key: string;
            }
        >;
        images?: Array<{
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: 'image';
          _key: string;
        }>;
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: 'category';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      type?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'tag';
      }>;
      slug?: Slug;
      description?: string;
    }
  | {
      _id: string;
      _type: 'concertType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      heading?: string;
      slug?: Slug;
      buyTicketLink?: string;
      available?: boolean;
      icon?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      };
      images?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      eventVideos?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'video';
      }>;
      date?: string;
      subHeading?: string;
      description?: string;
      location?: string;
    }
  | {
      _id: string;
      _type: 'contactForm';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      userId?: string;
      registeredName?: string;
      registeredEmail?: string;
      firstName?: string;
      lastName?: string;
      email?: string;
      phoneNumber?: string;
      message?: string;
    }
  | {
      _id: string;
      _type: 'contactInfo';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: string;
      heading?: string;
      contacts?: Array<{
        title?: string;
        phone?: string;
        email?: string;
        other?: string;
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: 'design';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      presentation?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      thumbnail?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      };
      images?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: 'ekontSenderDetails';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      senderClient?: {
        name?: string;
        phones?: Array<string>;
        email?: string;
      };
      senderAddress?: {
        city?: string;
        postCode?: string;
        street?: string;
        num?: string;
        other?: string;
      };
      senderDeliveryType?: 'delivery' | 'office';
      cdOptions?: {
        method?: 'bank';
        bic?: string;
        iban?: string;
        bankCurrency?: 'BGN' | 'EUR';
        payDays?: number;
      };
      senderOfficeCode?: string;
      payAfterAccept?: '0' | '1';
      payAfterTest?: '0' | '1';
      shipmentDescription?: string;
      paymentSenderMethod?: 'cash' | 'credit';
      paymentSenderAmount?: string;
      paymentReceiverMethod?: 'cash';
      paymentReceiverAmount?: string;
      returnInstructionParams?: {
        type?: 'return';
        returnParcelDestination?: string;
        returnParcelPaymentSide?: 'receiver' | 'sender';
        returnParcelReceiverOfficeCode?: string;
      };
    }
  | {
      _id: string;
      _type: 'esotericaStore';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      Name?: string;
      slug?: Slug;
      type?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'tag';
      }>;
      images?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      productVideo?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'video';
      };
      description?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      price?: number;
      discount?: number;
      category?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'category';
      }>;
      stock?: number;
      showSizes?: boolean;
      sizes?: Array<string>;
    }
  | {
      _id: string;
      _type: 'eventsType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      heading?: string;
      slug?: Slug;
      available?: boolean;
      icon?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      };
      images?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      eventVideos?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'video';
      }>;
      date?: string;
      subHeading?: string;
      description?: string;
      location?: string;
      contactFormHeading?: string;
      messages?: Array<{
        name?: string;
        email?: string;
        phone?: string;
        message?: string;
        createdAt?: string;
        _type: 'message';
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: 'musicStore';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      Name?: string;
      type?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'tag';
      }>;
      slug?: Slug;
      images?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      productVideo?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'video';
      };
      description?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      price?: number;
      discount?: number;
      category?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'category';
      }>;
      stock?: number;
      showSizes?: boolean;
      sizes?: Array<string>;
    }
  | {
      _id: string;
      _type: 'order';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      orderNumber?: string;
      stripeCheckoutSessionId?: string;
      stripeCustomerId?: string;
      clerkUserId?: string;
      customerDetails?: {
        customerName?: string;
        customerEmail?: string;
        customerPhone?: string;
      };
      customerAddress?: {
        country?: string;
        city?: string;
        officeCode?: string;
        zip?: string;
        street?: string;
        streetNumber?: string;
        other?: string;
      };
      stripePaymentIntentId?: string;
      products?: Array<{
        product?:
          | {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'esotericaStore';
            }
          | {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'musicStore';
            };
        quantity?: number;
        selectedSize?: string;
        _key: string;
      }>;
      totalPrice?: number;
      currency?: string;
      deliveryMethod?: string;
      paymentMethod?: string;
      status?:
        | 'canceled'
        | 'failed'
        | 'inProgress'
        | 'pending'
        | 'ready'
        | 'refunded'
        | 'send';
      wasLabelPatched?: boolean;
      labelURL?: string;
      labelAsset?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        _type: 'file';
      };
      orderDate?: string;
    }
  | {
      _id: string;
      _type: 'salesType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      description?: string;
      discountAmount?: number;
      couponCode?: string;
      validFrom?: string;
      validUntil?: string;
      isActive?: boolean;
    }
  | {
      _id: string;
      _type: 'sanity.fileAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      source?: SanityAssetSourceData;
    }
  | {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    }
  | {
      _id: string;
      _type: 'soundcloudType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      trackId?: string;
    }
  | {
      _id: string;
      _type: 'tag';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
    }
  | {
      _id: string;
      _type: 'titleDescriptionType';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      heading?: string;
      description?: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
            listItem?: 'bullet';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }
        | {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: 'image';
            _key: string;
          }
      >;
      floatingImage?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: 'video';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      url?: string;
      thumbnail?: Array<{
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      videoFile?: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        _type: 'file';
      };
    }
  | {
      _id: string;
      _type: 'youtubeVideos';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      category?: 'esoterica' | 'music';
      videoTitle?: string;
      url?: string;
    }
>;

// Source: ./sanity/lib/sales/getWeekSaleByCouponCode.ts
// Variable: WEEK_SALE_QUERY
// Query: *[_type == "salesType" && couponCode == $couponCode && isActive == true] | order(validFrom desc)[0]
export type WEEK_SALE_QUERYResult = {
  _id: string;
  _type: 'salesType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
} | null;

// Source: ./sanity/lib/sections/getTitleAndDescriptions.ts
// Variable: TITLE_AND_DESCRIPTIONS_QUERY
// Query: *[_type == "titleDescriptionType"][0]
export type TITLE_AND_DESCRIPTIONS_QUERYResult = {
  _id: string;
  _type: 'titleDescriptionType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heading?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
  floatingImage?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
} | null;

// Source: ./sanity/lib/tags/getAllTags.ts
// Variable: ALL_TAGS_QUERY
// Query: *[ _type == "tag"]
export type ALL_TAGS_QUERYResult = Array<{
  _id: string;
  _type: 'tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
}>;

// Source: ./sanity/lib/youtube/getSoundCloud.ts
// Variable: SOUND_CLOUD_QUERY
// Query: *[ _type == "soundcloudType"]
export type SOUND_CLOUD_QUERYResult = Array<{
  _id: string;
  _type: 'soundcloudType';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  trackId?: string;
}>;

// Source: ./sanity/lib/youtube/getYouTubeVids.ts
// Variable: YOU_TUBE_VIDS_QUERY
// Query: *[_type == "youtubeVideos"] | order(title asc) {      category,      videoTitle,      url    }
export type YOU_TUBE_VIDS_QUERYResult = Array<{
  category: 'esoterica' | 'music' | null;
  videoTitle: string | null;
  url: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n    *[_type == "bannerType" && slug == $slug][0]\n  ': BANNER_BY_TITLE_QUERYResult;
    '\n    \n    *[ _type == "category"] \n    \n    ': ALL_CATEGORIES_QUERYResult;
    '\n    *[_type == "category" && references(*[_type == "tag" && _id == $tags]._id)] | order(Name asc) \n  ': ALL_CATEGORIES_QUERY_BY_TAGResult;
    '\n    *[ _type == "contactInfo" && slug == $slug][0]': CONTACT_CARDS_QUERYResult;
    '\n    *[ _type == "cardsType" && slug.current == $slug][0]': PAGE_CARDS_QUERYResult;
    '\n  *[ _type == "ekontSenderDetails"] \n  ': EKONT_SENDER_DETAILS_QUERYResult;
    '\n    \n    *[ _type == "concertType"] | order(_createdAt asc) \n    \n    ': CONCERTS_QUERYResult;
    '\n    \n    *[ _type == "concertType" && slug.current == $slug] | order(_createdAt desc)[0] \n    ': CONCERTS_QUERY_BY_SLUGResult;
    '\n    \n    *[ _type == "eventsType"] | order(_createdAt asc) \n   { ...,\n    "messages": undefined\n    }\n    ': EVENTS_QUERYResult;
    '\n    \n    *[ _type == "eventsType" && slug.current == $slug] | order(_createdAt desc) [0] {\n\n      ...,\n      "messages": undefined\n    }\n    ': EVENTS_QUERY_BY_SLUGResult;
    '\n  *[_type == "favoriteProducts" && userId == $userId][0] {\n    ...,\n    userId,\n    itemId[]-> {\n      _id,\n      Name,\n      ...,\n    }\n  }\n    ': FAVORITE_PRODUCTS_QUERYResult;
    '\n      *[_type == "order" && clerkUserId == $userId] | order(_createdAt desc) {\n        ...,\n        products[]{\n          ...,\n          product->\n        },\n      }\n    ': ORDERS_QUERYResult;
    '\n    *[_type == "musicStore" || _type == "esotericaStore" ] | order(Name asc) {\n  Name,\n  stock,\n  price,\n  discount,\n  _id,\n  image,\n  images[]{\n        asset->,\n        hotspot,\n        crop,\n        _type,\n        _key\n      },\n  slug,\n  category[]->{title}\n}\n    ': ALL_PRODUCTS_QUERYResult;
    '\n    *[_type == "esotericaStore"] | order(Name asc) {\n      Name,\n      stock,\n      price,\n      discount,\n      _id,\n      image,\n      images[]{\n        asset->,\n        hotspot,\n        crop,\n        _type,\n        _key\n      },\n      slug,\n      showSizes,\n      sizes,\n      category[]->{title},\n      _type,    \n      _createdAt,\n      _updatedAt,\n      _rev,\n      // images[]->,\n      // productVideo->,\n        \n    }\n  ': ESOTERICA_PRODUCTS_QUERYResult;
    '\n    *[_type == "musicStore"] | order(Name asc) {\n      Name,\n      stock,\n      price,\n      discount,\n      _id,\n      image,\n      images[]{\n        asset->,\n        hotspot,\n        crop,\n        _type,\n        _key\n      },\n      slug,\n      showSizes,\n      sizes,\n      category[]->{title},\n      _type,    \n      _createdAt,\n      _updatedAt,\n      _rev,\n      // images[]->,\n      // productVideo->,\n      \n    }\n  ': MUSIC_PRODUCTS_QUERYResult;
    '\n  *[\n  _type in ["musicStore", "esotericaStore"] && slug.current == $slug\n] | order(Name asc) [0] {\n  ...,\n  category[]->,\n  images[]{\n    asset->,\n    hotspot,\n    crop,\n    _type,\n    _key\n  },\n  productVideo->{\n    _id,\n    _type,\n    title,\n    \'videoFile\': videoFile.asset->{\n      url\n    },\n    \'thumbnail\': thumbnail[].asset->{\n      url\n    },\n  }\n}\n\n  //  *[_type in ["musicStore", "esotericaStore"] && slug.current == $slug] | order(Name asc) [0] {\n  //     ...,\n  //     category[]->,\n  //     images[]{\n  //       asset->,\n  //       hotspot,\n  //       crop,\n  //       _type,\n  //       _key\n  //     },\n  //     productVideo->{\n  //       // thumbnail[]{\n  //       //   asset->{url}\n  //       // },\n  //       // videoFile->{\n  //       //   asset->{url}\n  //       // }\n  //       ...,\n  //       \'thumbnail\': thumbnail[].asset->,\n  //       \'videoFile\': videoFile.asset->\n  //     }\n  //   }\n  \n    \n    ': PRODUCT_BY_SLUG_QUERYResult;
    '\n    *[\n      _type in ["musicStore", "esotericaStore", "concertType", "eventsType"] \n      && Name match $searchParams || title match $searchParams || heading match $searchParams || subHeading match $searchParams || location match $searchParams || description match $searchParams\n      || pt::text(description) match $searchParams\n      ] | order(Name asc) \n    ': SEARCH_PRODUCTS_BY_NAME_QUERYResult;
    '\n    *[_type == "salesType" && couponCode == $couponCode && isActive == true] | order(validFrom desc)[0]\n    ': WEEK_SALE_QUERYResult;
    '\n    \n    *[_type == "titleDescriptionType"][0] \n    \n    ': TITLE_AND_DESCRIPTIONS_QUERYResult;
    '\n    \n    *[ _type == "tag"] \n    \n    ': ALL_TAGS_QUERYResult;
    '\n    *[ _type == "soundcloudType"] \n    ': SOUND_CLOUD_QUERYResult;
    '\n    \n    *[_type == "youtubeVideos"] | order(title asc) {\n      category,\n      videoTitle,\n      url\n    } \n    \n    ': YOU_TUBE_VIDS_QUERYResult;
  }
}
